In [191]:
# importing necesssory dependencies
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# ignoring the unnecessory warnings
import warnings
warnings.filterwarnings(action="ignore")

In [192]:
# importing the dataframe
df = pd.read_csv("/content/Meteorite_Landings.csv")

In [193]:
# Aceessing the first five column
df["name"].head()

0      Aachen
1      Aarhus
2        Abee
3    Acapulco
4     Achiras
Name: name, dtype: object

In [194]:
# pritning the columns of the dataframe
df.columns

Index(['name', 'id', 'nametype', 'recclass', 'mass (g)', 'fall', 'year',
       'reclat', 'reclong', 'GeoLocation'],
      dtype='object')

In [195]:
# lets check the missing values of the dataframe
df.isna().sum()

name              0
id                0
nametype          0
recclass          0
mass (g)        131
fall              0
year            291
reclat         7315
reclong        7315
GeoLocation    7315
dtype: int64

In [196]:
# datatypes of the features columns
df.dtypes

name            object
id               int64
nametype        object
recclass        object
mass (g)       float64
fall            object
year            object
reclat         float64
reclong        float64
GeoLocation     object
dtype: object

In [197]:
# description of the table
df.describe(include="all").transpose()

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
name,45716,45716,Aachen,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id,45716.0,NaN,NaN,NaN,26889.735104,16860.68303,1.0,12688.75,24261.5,40656.75,57458.0
nametype,45716,2,Valid,45641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
recclass,45716,466,L6,8285,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mass (g),45585.0,NaN,NaN,NaN,13278.078549,574988.87641,0.0,7.2,32.6,202.6,60000000.0
fall,45716,2,Found,44609,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,45425,266,01/01/2003 12:00:00 AM,3323,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reclat,38401.0,NaN,NaN,NaN,-39.12258,46.378511,-87.36667,-76.71424,-71.5,0.0,81.16667
reclong,38401.0,NaN,NaN,NaN,61.074319,80.647298,-165.43333,0.0,35.66667,157.16667,354.47333
GeoLocation,38401,17100,"(0.0, 0.0)",6214,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [199]:
# Lets check wheather the id column in this constant or not
df.shape

(45716, 10)

In [158]:
# Frequency of the name type in the dataframe
df["nametype"].value_counts()

Valid     45641
Relict       75
Name: nametype, dtype: int64

In [211]:
result = df.query("`mass (g)` >= 100 and fall == 'Fell'")

In [212]:
result.head()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"
5,Adhi Kot,379,Valid,EH4,4239.0,Fell,01/01/1919 12:00:00 AM,32.10000,71.80000,"(32.1, 71.8)"

In [175]:
import requests
response = requests.get('https://data.nasa.gov/resource/gh4g-9sfh.json', params={"$limit":500_00})

if response.ok:
  payload = response.json()
else:
  print(f"request was not sucessful and returned code: {response.status_code}")
  payload = None

In [176]:
# importing the dataframe
df = pd.DataFrame(payload)

In [177]:
df.head()

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,geolocation,:@computed_region_cbhk_fwbd,:@computed_region_nnqa_25f4
0,Aachen,1,Valid,L5,21,Fell,1880-01-01T00:00:00.000,50.775000,6.083330,"{'latitude': '50.775', 'longitude': '6.08333'}",NaN,NaN
1,Aarhus,2,Valid,H6,720,Fell,1951-01-01T00:00:00.000,56.183330,10.233330,"{'latitude': '56.18333', 'longitude': '10.23333'}",NaN,NaN
2,Abee,6,Valid,EH4,107000,Fell,1952-01-01T00:00:00.000,54.216670,-113.000000,"{'latitude': '54.21667', 'longitude': '-113.0'}",NaN,NaN
3,Acapulco,10,Valid,Acapulcoite,1914,Fell,1976-01-01T00:00:00.000,16.883330,-99.900000,"{'latitude': '16.88333', 'longitude': '-99.9'}",NaN,NaN
4,Achiras,370,Valid,L6,780,Fell,1902-01-01T00:00:00.000,-33.166670,-64.950000,"{'latitude': '-33.16667', 'longitude': '-64.95'}",NaN,NaN

In [178]:
df.shape

(45716, 12)

In [179]:
df.columns

Index(['name', 'id', 'nametype', 'recclass', 'mass', 'fall', 'year', 'reclat',
       'reclong', 'geolocation', ':@computed_region_cbhk_fwbd',
       ':@computed_region_nnqa_25f4'],
      dtype='object')

In [180]:
df.dtypes

name                           object
id                             object
nametype                       object
recclass                       object
mass                           object
fall                           object
year                           object
reclat                         object
reclong                        object
geolocation                    object
:@computed_region_cbhk_fwbd    object
:@computed_region_nnqa_25f4    object
dtype: object

In [181]:
df.tail(n = 1)

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,geolocation,:@computed_region_cbhk_fwbd,:@computed_region_nnqa_25f4
45715,Zulu Queen,30414,Valid,L3.7,200,Found,1976-01-01T00:00:00.000,33.983330,-115.683330,"{'latitude': '33.98333', 'longitude': '-115.68...",8,1177

In [182]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45716 entries, 0 to 45715
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         45716 non-null  object
 1   id                           45716 non-null  object
 2   nametype                     45716 non-null  object
 3   recclass                     45716 non-null  object
 4   mass                         45585 non-null  object
 5   fall                         45716 non-null  object
 6   year                         45425 non-null  object
 7   reclat                       38401 non-null  object
 8   reclong                      38401 non-null  object
 9   geolocation                  38401 non-null  object
 10  :@computed_region_cbhk_fwbd  1659 non-null   object
 11  :@computed_region_nnqa_25f4  1659 non-null   object
dtypes: object(12)
memory usage: 4.2+ MB

In [167]:
df.iloc[100:104,[0,3,4,5]]

              name       recclass   mass  fall
100         Benton            LL6   2840  Fell
101         Berduc             L6    270  Fell
102         Béréba  Eucrite-mmict  18000  Fell
103  Berlanguillas             L6   1440  Fell

In [183]:
df.dtypes

name                           object
id                             object
nametype                       object
recclass                       object
mass                           object
fall                           object
year                           object
reclat                         object
reclong                        object
geolocation                    object
:@computed_region_cbhk_fwbd    object
:@computed_region_nnqa_25f4    object
dtype: object

In [169]:
df["fall"] == "Fall"

0        False
1        False
2        False
3        False
4        False
         ...
45711    False
45712    False
45713    False
45714    False
45715    False
Name: fall, Length: 45716, dtype: bool

In [174]:
df.head()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [ ]:
df.columns

Index(['name', 'id', 'nametype', 'recclass', 'mass', 'fall', 'year', 'reclat',
       'reclong', 'geolocation', ':@computed_region_cbhk_fwbd',
       ':@computed_region_nnqa_25f4'],
      dtype='object')

In [ ]:
df["mass"].median()

32.6

In [ ]:
df['mass (g)'].max()

60000000.0

In [ ]:
df["mass (g)"].nunique()

12576

In [ ]:
df.recclass.unique()[:14]

array(['L5', 'H6', 'EH4', 'Acapulcoite', 'L6', 'LL3-6', 'H5', 'L',
       'Diogenite-pm', 'Unknown', 'H4', 'H', 'Iron, IVA', 'CR2-an'],
      dtype=object)